/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nn_project;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ThinkPad
 */
public class NN_Frame extends javax.swing.JFrame {

    public NN_Frame() {
        //   System.out.print("hi");
        initComponents();

    }
    public String[] names = {"AND.JPG", "OR.JPG", "NAND.JPG", "NOR.JPG", "XOR.JPG", "XNOR.JPG"};
    public Icon[] icons = {new ImageIcon(getClass().getResource(names[0])), 
        new ImageIcon(getClass().getResource(names[1])),
        new ImageIcon(getClass().getResource(names[2])),
        new ImageIcon(getClass().getResource(names[3])),
        new ImageIcon(getClass().getResource(names[4])),
        new ImageIcon(getClass().getResource(names[5]))
    };

    /**
     * Creates new form NN_Frame
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        structureLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        stopText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 204));
        panel.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logic Operators using Neural Network");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panel.add(jLabel2);
        jLabel2.setBounds(200, 20, 630, 70);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose One From Logic gates:");
        panel.add(jLabel3);
        jLabel3.setBounds(10, 160, 290, 25);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nn_project/AND.jpg"))); // NOI18N
        panel.add(iconLabel);
        iconLabel.setBounds(690, 160, 230, 160);

        combobox.setBackground(new java.awt.Color(204, 204, 255));
        combobox.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        combobox.setForeground(new java.awt.Color(0, 51, 102));
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                    AND", "                    OR", "                    NAND", "                    NOR", "                    XOR", "                    XNOR" }));
        combobox.setAlignmentX(10.0F);
        combobox.setAlignmentY(10.0F);
        combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                whenChanged(evt);
            }
        });
        panel.add(combobox);
        combobox.setBounds(350, 160, 260, 40);

        structureLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        structureLabel.setForeground(new java.awt.Color(255, 255, 255));
        structureLabel.setText("The Network Struture is: Perceptron.");
        panel.add(structureLabel);
        structureLabel.setBounds(630, 330, 340, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Solve it");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(680, 480, 240, 60);
        panel.add(stopText);
        stopText.setBounds(680, 420, 240, 40);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   Stop criteria : Max Number of Epoch :");
        panel.add(jLabel5);
        jLabel5.setBounds(280, 420, 390, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nn_project/4.jpg"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void whenChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_whenChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) 
        {
            iconLabel.setIcon(icons[combobox.getSelectedIndex()]);
        }
        if (combobox.getSelectedIndex() == 4 || combobox.getSelectedIndex() == 5) {
            structureLabel.setText("The Network Struture is: Multi-Layer.");
        } else {
            structureLabel.setText("The Network Struture is: Perceptron.");
        }


    }//GEN-LAST:event_whenChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        gateFrame frame = new gateFrame();
        frame.getEpochNum(Integer.parseInt(stopText.getText()));
        frame.setVisible(true);
        String title = combobox.getSelectedItem().toString();
        frame.setTitle(title + " Gate");
        frame.titleLabel.setText("      Solving".trim() + "  " + title.trim() + "  " + "gate Using Neural   Network");

        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NN_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField stopText;
    private javax.swing.JLabel structureLabel;
    // End of variables declaration//GEN-END:variables
}
